/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tablajava;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Writer;
import java.util.List;

import technology.tabula.Page;
import technology.tabula.Table;
import technology.tabula.extractors.BasicExtractionAlgorithm;
import technology.tabula.extractors.SpreadsheetExtractionAlgorithm;
import technology.tabula.writers.CSVWriter;
import technology.tabula.writers.JSONWriter;

public class App {
    public void extractPdf(){
        // PDFのパス
        String path = "src\\main\\resources\\20.pdf";
        // 出力先CSVのパス
        String outputPath = "src\\main\\resources\\output.csv";

        // PDF内のテーブルの座標
        float top = 156f;       // y1
        float left = 96f;       // x1
        float bottom = 508f;    // y2
        float right = 506;      // x2

        try{
            // PDFの取得
            Page page = Utils.getAreaFromFirstPage(path, top, left, bottom, right);

            // 読み込み用のクラス
            BasicExtractionAlgorithm sea = new BasicExtractionAlgorithm();
            
            // テーブルの抽出
            List<Table> tables = (List<Table>) sea.extract(page);

            StringBuilder sb = new StringBuilder();
            (new CSVWriter()).write(sb, tables);

            // CSVの書き込み
            PrintWriter pw = new PrintWriter(new File(outputPath));
            pw.write(sb.toString());
            pw.close();

            System.out.println(sb.toString());

        }catch(IOException e ){
            e.printStackTrace();
        }

    }

    public static void main(String[] args) {
        new App().extractPdf();
    }
}
